version: '3'

services:
    web-nginx:
        image: nginx:alpine
        container_name: mywebsite
        restart: always
        volumes:
            - "./restaurant:/usr/share/nginx/html:ro"
            - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
        ports:
            - 80:8080
        

        
    cadvisor:
        image: google/cadvisor:latest
        links:
            - web-nginx:mywebsite
        restart: always
        ports:
            - "9000:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro