version: '3'

services:
    web-nginx:
        image: nginx:alpine
        container_name: mywebsite
        restart: always
        volumes:
            - "./restaurant:/usr/share/nginx/html:ro"
            - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
        ports:
            - 80:8080
            