version: '3'

services:
    web-nginx:
        image: nginx:alpine
        container_name: mywebsite
        restart: always
        volumes:
            - "./restaurant:/usr/share/nginx/html:ro"
            - "./default.conf:/etc/nginx/conf.d/default.conf:ro"
        ports:
            - 80:8080
        

        
    cadvisor:
        image: google/cadvisor:latest
        links:
            - web-nginx:mywebsite
        restart: always
        ports:
            - "8000:8080"
        volumes:
            - /:/rootfs:ro
            - /var/run:/var/run:rw
            - /sys:/sys:ro
            - /var/lib/docker/:/var/lib/docker:ro
            
    portainer:
        image: portainer/portainer
        links:
            - web-nginx:mywebsite
        restart: always
        container_name: "portainer-app"
    #Automatically choose 'Manage the Docker instance where Portainer is running' by adding <--host=unix:///var/run/docker.sock> to the command
      #  networks:
       #     - local
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /opt/portainer/data:/data
        
        # ports:
            # - 9000:9000
            